# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: setyoputra2005@gmail.com
author_name: Putra Setyo
contract_name: asa_marketplace
deployment_language: python
preset_name: starter
project_name: ASA_Marketplace

